### ISSUE TITLE
Hash for Statement Conversion not found in REST API results

### ISSUE THREAD

**Issue by johnbachman** [indralab/indra_db#21]
Querying `api.host/statements/from_agents?agent0=ACSL4&format=html`

Triggers an error that manifests as a KeyError at this line in the HTML assembler (branch):

https://github.com/johnbachman/indra/blob/8c4cabd2470f81cf75873ba70d81cb3aaa69155d/indra/assemblers/html/assembler.py#L76

The error results from the following Conversion statement:

`Conversion(ACSL4(), [a long-chain fatty acid(), ATP(), coenzyme A()], [AMP(), diphosphate(), a long-chain acyl-CoA()])`

That has hash (calculated locally with `stmt.get_hash`): `3001908797546140`

This could be due to possible non-determinism in the JSON serialization/deserialization of reactant/product lists in Conversion statements.

**Comment by bgyori** [comment]
I think this might be the same issue as this: https://github.com/sorgerlab/indra/issues/659

**Comment by pagreene** [comment]
That would explain my lingering sense that there was a problem with conversions that I mentioned to John. I'll dig into this/these today.

**Comment by pagreene** [comment]
The cause of this bug is a change in the generation of the matches key several months ago, after some of the pre-assembled statements were generated.

**Comment by pagreene** [comment]
This has since been fixed as part of the major overhaul of the database.
